language: c

sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

matrix:
  include:

    - os: linux
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake

before_install:
  - eval "${MATRIX_EVAL}"
  - cd ..
  - pip install --user cpp-coveralls

install:
  - sudo apt-get install -qq gfortran
  - sudo apt-get install -qq openmpi-bin libopenmpi-dev

script:
  - cd SEISM-T
  - cmake .
  - make install
  - mpiexec -n 2 ./examples_01

after_success:
  - ${GCOV} -v
  - coveralls --gcov ${GCOV} --gcov-options '\-lp'
